ut-code/utcode-learn

docs/3-web-servers/02-node-js/index.md
React コンポーネント中の Markdown が正しく変換されていなかったので、修正しました。
=> Fix Markdown that is not converted

docs/4-advanced/01-fetch-api/index.md
Fetch API の説明で `/server.js` のコードが記載されていないので、何が行われているのかわかりにくくなっています。(`GitHub で表示` を押せば見れるが、少し面倒。)そのため、`/server.js` のコードを追記しました。
=> Add /server.js script in fetch API description

docs/3-web-servers/07-get-post/index.md
Markdown が正しく変換されないので、HTML に書き換えました。
=> Fix unconverted Markdown in 「GET リクエストと POST リクエスト」 section

.github/workflows/build-test.yml
ビルドテストが master ブランチ以外で動かなくしていたので、develop ブランチでも動くようにした。
=> Update build test action

.vscode/extensions.json, .vscode/settings.json, package.json
- `package.json` に `format` スクリプトを入れました。
- Prettier の VS Code 拡張機能をおすすめするようにしました。
- VS Code のフォーマッターを Prettier にセットしました。
=> Setup Prettier

docusaurus.config.js
言語が `"en"` になっていたので、`"ja"` に改めました。
i18n の設定を利用しています。https://docusaurus.io/docs/api/docusaurus-config#i18n
=> Set lang to `"ja"`

docs/2-browser-apps/04-class/index.md
- Markdown がレンダリングされていなかったので、直しました。これは、Docusaurus の仕様なので、HTML で書くしかないです。related with #143. (ちなみに、これを直す PR はマージされたので、Docusaurus 3.0 がリリースされるのを待つだけです。)
=> Fix unrendered Markdown

docs/2-browser-apps/04-class/index.md
- 前置詞を使う変数名は冗長なので避けたほうが良い。
試しに、`yearOfBirth` と `birthYear` で GitHub の検索機能を使って調べてみたところ、`birthYear` の方が圧倒的に多くなっていました。
`birthYear` = 160 K
`yearOfBirth` = 19 K
=> Rename yearOfBirth to birthYear

docs/1-trial-session/09-functions/index.md, src/components/Term/definitions.js
=> Rewrite functions

docs/1-trial-session/02-html/index.md
- 最新のPrettierの設定に合わせた。`prettier-ignore`があったせいで、ここだけ古いままになってしまっていた。なお、この`prettier-ignore`を消すと、`a`要素のフォーマットがかなりわかりにくくなるので消せない。
=> Format code of HTML section

docs/3-web-servers/05-form/index.md
=> Revert "fix critical typo"

docs/1-trial-session/07-if-statement/index.md, docs/1-trial-session/09-functions/index.md
個人的にif ~ elseは構文だと思ってるのでそのままにしてあります。
=> 「if 構文」を「if 文」に書き換え

docs/1-trial-session/09-functions/index.md
=> Remove unnecessary spaces

docs/1-trial-session/12-css/index.md, docs/2-browser-apps/05-css-arrangement/index.md, docs/6-exercise/4-css/index.md, src/components/Term/definitions.js
=> CSSのタイトルの修正

docs/3-web-servers/04-server/index.md, docs/3-web-servers/08-cookie/index.md, docs/4-advanced/01-fetch-api/index.md, docs/4-advanced/02-bundler/index.md
server.js が多く残ってる気がするので、そこはまた今度対応しようと思います
=> 第三~四章のコードブロックのタイトル修正

src/components/Answer/index.jsx, src/components/ExternalVideoPlayer/index.jsx, src/components/Term/index.jsx, src/components/ViewSource/index.jsx, src/pages/index.js, src/theme/MDXComponents.js
React 18から`React`のインポートが不要になったので、削除 #531
=> Remove import of React

docs/1-trial-session/01-get-started/index.mdx, docs/3-web-servers/02-node-js/index.mdx, docs/3-web-servers/09-git-github-init/index.mdx
MDX v3になったことにより、JSX内でのMarkdownのインデントが不要になり、前後の空行も不要になったので削除 #531
=> Remove indent in JSX

docs/2-browser-apps/01-inspector/index.mdx
機種によって、`fn/Fn`キーを押すかの有無が異なるので、削除しました。このキーの名前も機種によって異なるため。
=> Fix description of the inspector start command

docs/3-web-servers/03-module/index.mdx, docs/3-web-servers/04-server/index.mdx
`import { readFileSync } from "fs";`
のようにしてるので、多分動かない
それと `fs.writeFileSync` 関数を使って~ と書いてあるが、 サンプルコードでは `writeFileSync` 関数を使っていた (import {writeFileSync} のようにしているため)  ので  `readFileSync`  を使って～ に直した。
=> fs モジュールの関数から fs. を削除

docs/3-web-servers/03-module/index.mdx, docs/4-advanced/04-react/index.mdx
named importの説明を修正し、それに合わせて分割代入の説明をReactのセクションに後ろ倒ししました。
=> Fix description of named import

docs/1-trial-session/02-html/index.mdx, docs/1-trial-session/13-dom/index.mdx
`**` で囲んだ部分にインラインコードやタグが含まれており、かつ前後にスペースがない場合に太字にならないようだったので、いったん手動で前後にスペースを入れて修正しました。
=> 太字のスタイルが壊れている箇所を修正

docs/1-trial-session/05-variables/index.mdx
最初に出てくる変数の名前を `myGreatName` から `myName` に変更しました。
読者が "great" が入っている意図が分からず混乱することを防ぐためです。
=> 最初に出てくる変数の名前を `myGreatName` から `myName` に変更

docs/3-web-servers/04-module/index.mdx, docs/3-web-servers/05-server/index.mdx
`fs` モジュールと`fs` 標準モジュールの表記が混ざっていたので、統一しました。
`http` 標準モジュールの表記もそれに合わせて修正しました。
=> 標準モジュールの表記を統一

docs/2-browser-apps/03-class/_samples/car-class/script.js, docs/2-browser-apps/03-class/index.mdx
単位と数字の間には、半角スペースを入れないといけないという決まりがあります。(英語は分かち書きをすることから、日本語でもそうするという決まりになっています。)
一方で、一般的に日本語では分かち書きをしないため、日本語表記の単位は一般的な文脈では半角スペースを入れないこともあります。
ということで、表記を日本語にすることにより半角スペースを入れなくても間違いとは言えなくなるようにしました。
=> Carクラスを定義する問題での単位の表記を修正

.github/workflows/ci.yml
`actions/setup-node`のバージョンを最新にして、Node.jsのバージョンも`.nvmrc`から読むようにしました。
=> GitHub Actionsの設定をアップデート

docs/3-web-servers/06-form/index.mdx
`ViewSource`コンポーネントはすべての解答に置くことが想定されますが、この演習問題には置かれていなかったため設置しました。
=> 「フォーム」の章の`node-emoji`に関する演習問題に`ViewSource`コンポーネントを追加

docs/3-web-servers/04-module/_samples/date-fns/package-lock.json, docs/3-web-servers/04-module/_samples/date-fns/package.json, docs/4-advanced/02-bundler/_samples/run-npm-package-on-browsers/package-lock.json, docs/4-advanced/02-bundler/_samples/run-npm-package-on-browsers/package.json
#805 で、`date-fns`は破壊的な変更があることからアップデートを控えていましたが、ut.code(); Learnでは`date-fns`の機能をそれほど使っていなかったこととESM環境であったことが幸いし、特に影響はなかったためそのままアップデートしました。
cf. https://github.com/date-fns/date-fns/releases/tag/v3.0.0
=> `date-fns`パッケージを最新にアップデート

docs/3-web-servers/09-cookie/index.mdx
closes #813 
ついでに一箇所だけ地の文で cookie になっていたのを Cookie にしました。
=> Cookieの章の`set-cookie`を`Set-Cookie`に変更

docs/1-trial-session/03-css/_samples/first-css/index.html, docs/1-trial-session/03-css/index.mdx, package-lock.json, package.json
- **パッケージの更新**
- **CSS を style 属性を基本とする形に変更**
=> style属性を基本とする形に変更

docs/1-trial-session/03-css/index.mdx
- #841 でMDX中に不要な改行が挿入されたことでドキュメント中に不要な半角スペースが挿入されたため、不要な改行を削除 ([5d6a1e3](https://github.com/ut-code/utcode-learn/pull/848/commits/5d6a1e370c31289a16d63c3c1835a02700f978c9))
- タイポがあったため、修正 ([977cf5c](https://github.com/ut-code/utcode-learn/pull/848/commits/977cf5c6fffce1f1f942eaa6d0cc95d3880cc1f8))
=> 「CSS」の章のタイポ、スタイルの崩れを修正

docs/3-web-servers/08-database/_samples/forum/.gitignore
現在では`npx prisma init`で作成される`.gitignore`に`npx prisma generate`で生成されたファイルが記載されるようになりました。ここで、`/generated/prisma`という表記になっていたため、これに合わせるようにしました。
cf. https://www.prisma.io/docs/orm/reference/prisma-cli-reference#generated-assets
=> `.gitignore`での`/generated/prisma`の書き方をアップデート
