docs/3-golden-week/10-git/index.md

3-10 Git 修正

---

docs/1-trial-session/02-html/index.md
docs/1-trial-session/02-html/samples/form/index.html
docs/1-trial-session/05-variables/samples/compound-assignment/index.html
docs/1-trial-session/05-variables/samples/compound-assignment/script.js
docs/2-browser-apps/04-class/index.md
docs/2-browser-apps/04-class/samples/inheritance/index.html
docs/2-browser-apps/04-class/samples/inheritance/script.js
docs/2-browser-apps/04-class/samples/method/index.html
docs/2-browser-apps/04-class/samples/method/script.js
docs/2-browser-apps/05-array/index.md
docs/2-browser-apps/05-array/samples/Array-class/index.html
docs/2-browser-apps/05-array/samples/Array-class/script.js
docs/2-browser-apps/06-anonymous-function/index.md
docs/2-browser-apps/06-anonymous-function/samples/every/index.html
docs/2-browser-apps/06-anonymous-function/samples/every/script.js
docs/2-browser-apps/06-anonymous-function/samples/reduce/index.html
docs/2-browser-apps/06-anonymous-function/samples/reduce/script.js

trial-session/variablesのリンク先が消えていたので修正
browser-apps/classのメソッドの課題のリンクが切れていたので修正
browser-apps/classの継承の課題のリンクが切れていたので修正
browser-apps/arrayのArrayクラスの課題のリンクが切れていたので修正
browser-apps/anonymous-functionの課題のリンクが切れていたので修正

解答のリンクが切れているものを全て修正

---

docs/2-browser-apps/02-constant/index.md
docs/2-browser-apps/03-loop/index.md
docs/2-browser-apps/04-class/index.md
docs/2-browser-apps/05-array/index.md
docs/2-browser-apps/06-anonymous-function/index.md
docs/2-browser-apps/07-advanced-css/index.md
docs/3-web-servers/03-module/index.md
docs/3-web-servers/04-http-server/index.md
docs/4-advanced/03-typescript/index.md
src/components/Answer/index.jsx

- Create Answer component that hide an answer
- Replace HTML with MDX using Answer component

Replace html with markdown

---

docs/2-browser-apps/03-loop/_samples/answer-while/script.js

複合代入演算子の説明をする前に複合代入演算子が使われていたので、複合代入演算子を使わないコードに書き換えておきました。

Revise sample answer of while

---

docs/1-trial-session/07-if-statement/index.md

Reverts ut-code/utcode-learn#119

Revert "Ifelse"

---

docs/4-advanced/02-bundler/index.md
docs/4-advanced/04-react/index.md

Vite 4 になっていくつか変更点があったので、修正しました。

Update Vite description

---

docs/3-web-servers/06-form/_samples/book-search-system/static/index.html
docs/3-web-servers/06-form/_samples/book-search-system/template.ejs
docs/3-web-servers/07-get-post/_samples/bulletin-board/template.ejs

- フォームの解答の不要な `id` を削除しました。
- フォームの解答で `div` タグになっていたので、`li` タグに書き換えました。
- GET リクエストと POST リクエストの解答も同様に `li` タグに書き換えました。

Revise answers of form and get-post

---

docs/4-advanced/03-typescript/index.md

TypeScript の答えが分かりにくいので、とりあえず少しだけ TypeScript の答えを改善しました。まだ分かりにくいので、後でもう少し改善します。

Improve TypeScript answers

---

docs/1-trial-session/02-html/index.md
docs/1-trial-session/05-variables/index.md
docs/1-trial-session/06-boolean/index.md
docs/1-trial-session/07-if-statement/index.md
docs/1-trial-session/08-functions/index.md
docs/1-trial-session/09-css/index.md
docs/1-trial-session/10-object/index.md
docs/1-trial-session/11-dom/index.md
docs/1-trial-session/13-project/index.md
docs/2-browser-apps/02-constant/index.md
docs/2-browser-apps/03-loop/index.md
docs/2-browser-apps/04-class/index.md
docs/2-browser-apps/05-array/index.md
docs/2-browser-apps/06-anonymous-function/index.md
docs/2-browser-apps/07-advanced-css/index.md
docs/2-browser-apps/07-css-arrangement/index.md
docs/2-browser-apps/09-project/index.md
docs/3-web-servers/03-module/index.md
docs/3-web-servers/04-http-server/index.md
docs/3-web-servers/05-template-engine/index.md
docs/3-web-servers/06-form/index.md
docs/3-web-servers/07-get-post/index.md
docs/3-web-servers/08-database/index.md
docs/4-advanced/01-fetch-api/index.md
docs/4-advanced/02-bundler/index.md
docs/4-advanced/03-typescript/index.md
docs/4-advanced/04-react/index.md
src/components/ViewSource/index.jsx

`docs` フォルダ以外で使えないというバグがあったので、とりあえず Revert します。直ったら、また PR を送ります。

Revert #126

---

docs/3-web-servers/12-deploy-on-render/index.md

Update PORT description

---

src/pages/exercise/ryoma/index.md

36行目に軽微な修正

---

src/pages/exercise/lecture5/position/_samples/1_fixed/index.html
src/pages/exercise/lecture5/position/_samples/1_fixed/style.css
src/pages/exercise/lecture5/position/_samples/2_relative-absolute/index.html
src/pages/exercise/lecture5/position/_samples/2_relative-absolute/style.css
src/pages/exercise/lecture5/position/_samples/3_sticky/index.html
src/pages/exercise/lecture5/position/_samples/3_sticky/style.css

すぐマージします
- 枠線が重ならないように修正
- 色やpaddingなどを調整

positionの課題を修正

---

src/components/Term/definitions.js

#233 でのエラーを直しました。緊急性が高いので、レビュー待たずにそのままマージします。

Fix build error

---

docs/1-trial-session/13-project/_samples/stopwatch/script.js
docs/1-trial-session/13-project/index.md
docs/2-browser-apps/03-loop/index.md

- 複合代入演算子の説明をはやめたことで、何箇所かで複合代入演算子を使うことができるようになりましたが、使用されていない場所があったので、使用するようにしました。

Use compound assignment operator

---

docs/1-trial-session/10-object/index.md

Fix broken link

---

docs/2-browser-apps/08-css-arrangement/index.md

- CSS の練習問題で使用されていないプロパティがいくつかあったので、削除しました。

Remove unused properties from CSS exercise

---

docs/2-browser-apps/08-css-arrangement/_samples/absolute/style.css
docs/2-browser-apps/08-css-arrangement/_samples/fixed/style.css
docs/2-browser-apps/08-css-arrangement/_samples/relative/style.css

- `box1` だけ `background-color` が最後に宣言されていて、一人ぼっちで可愛そうなので、みんなと同じ順番にしてあげました。

Unify CSS order

---

docs/1-trial-session/10-array/index.md

arrayの節で習ってない単語が出てくることの修正

---

docs/3-web-servers/06-form/index.md

URIエンコードです。URLエンコードではないです

---

docs/1-trial-session/01-get-started/index.md

- Google Chromeのインストール方法を追加
- Visual Studio Codeのインストール方法をmacOSとWindows両方に対応

Update description of installation in get-started

---

src/components/Term/definitions.js

and fix some confusing explanation

add examples to naming convention in definition.js

---

docs/1-trial-session/06-boolean/_samples/weird-comparison/script.js
docs/1-trial-session/06-boolean/index.md
docs/1-trial-session/07-if-statement/_samples/the-right-to-vote/script.js
docs/1-trial-session/07-if-statement/index.md
docs/1-trial-session/11-object/_samples/incrementAge/script.js
docs/1-trial-session/11-object/index.md
docs/1-trial-session/13-dom/_samples/css/script.js
docs/1-trial-session/13-dom/_samples/get-element-by-id/script.js
docs/1-trial-session/13-dom/index.md
docs/1-trial-session/14-events/index.md
docs/1-trial-session/15-project/_samples/omikuji/script.js
docs/1-trial-session/15-project/_samples/stopwatch/script.js
docs/1-trial-session/15-project/index.md
docs/2-browser-apps/01-inspector/index.md
docs/6-exercise/1-basis-of-web/index.md
docs/6-exercise/2-easy-apps/_samples/bmi/script.js
docs/6-exercise/2-easy-apps/_samples/calculator/script.js
docs/6-exercise/2-easy-apps/_samples/drawing/answer/script.js
docs/6-exercise/2-easy-apps/_samples/drawing/event-demo/script.js
docs/6-exercise/2-easy-apps/_samples/object-event/script.js
docs/6-exercise/2-easy-apps/index.md
docs/6-exercise/3-javascript/index.md
docs/6-exercise/5-browser-apps/_samples/flashcard/script.js
docs/6-exercise/5-browser-apps/index.md

Migrate from `let` to `const`

---

.github/workflows/ci.yml
package.json

- Prettierでのフォーマットが行われているかを自動でチェックするCIを作成した。

Add CI of Prettier

---

docs/2-browser-apps/06-project/_samples/todo/script.js
docs/2-browser-apps/06-project/index.mdx

addbutton が新しい todo を作ったときに disabled になっていなかった

演習問題バグ修正 (todo)

---

docs/1-trial-session/07-if-statement/index.mdx
docs/2-browser-apps/01-inspector/index.mdx
docs/2-browser-apps/04-anonymous-function/index.mdx
docs/2-browser-apps/05-css-arrangement/index.mdx
docs/2-browser-apps/06-project/index.mdx
docs/3-web-servers/02-node-js/index.mdx
docs/3-web-servers/03-module/index.mdx
docs/3-web-servers/04-server/index.mdx
docs/3-web-servers/05-form/index.mdx
docs/3-web-servers/08-cookie/index.mdx
docs/4-advanced/04-react/index.mdx
docs/6-exercise/1-basis-of-web/index.mdx
docs/6-exercise/2-easy-apps/index.mdx
docs/6-exercise/3-javascript/index.mdx
docs/6-exercise/4-css/index.mdx
docs/6-exercise/5-browser-apps/index.mdx
docs/6-exercise/8-database-and-cookie/index.mdx

動いてなかったです。
例: https://learn.utcode.net/docs/web-servers/module/#%E5%88%A5%E3%81%AE%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AB%E6%9B%B8%E3%81%8B%E3%82%8C%E3%81%9F%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0

コードブロックのタイトルにダブルクォーテーション追加

---

src/components/Term/definitions.js

モジュールとライブラリの違いは自分でもよくわかってないので間違ってたら修正して下さい。

ライブラリの説明の修正　

---

docs/3-web-servers/03-module/index.mdx

require -> import

---

docs/3-web-servers/04-server/index.mdx
docs/3-web-servers/05-form/_samples/book-search-system/main.mjs
docs/3-web-servers/05-form/_samples/book-search-system/send.html
docs/3-web-servers/06-get-post/_samples/forum/index.html
docs/3-web-servers/06-get-post/_samples/forum/main.mjs
docs/3-web-servers/07-database/_samples/forum/index.html
docs/3-web-servers/07-database/_samples/forum/main.mjs
docs/3-web-servers/08-cookie/_samples/profile/index.html
docs/3-web-servers/08-cookie/_samples/profile/login.html
docs/3-web-servers/08-cookie/_samples/profile/main.mjs
docs/3-web-servers/08-cookie/_samples/profile/profile.html
docs/3-web-servers/08-cookie/_samples/profile/register.html

なんか検索かけても少ないのでうまくマージされてない可能性があります

{variable} -> <!-- variable -->

---

docs/3-web-servers/02-node-js/index.mdx

Update installation of Node.js

---

docs/3-web-servers/03-module/_samples/read-file-sync/main.mjs
docs/3-web-servers/03-module/_samples/write-file-sync/main.mjs
docs/3-web-servers/03-module/index.mdx
docs/3-web-servers/04-server/_samples/ejs-template-engine/main.js
docs/3-web-servers/04-server/_samples/static-hosting-naive/main.mjs
docs/3-web-servers/04-server/index.mdx
docs/3-web-servers/05-form/_samples/book-search-system/main.mjs
docs/3-web-servers/06-get-post/_samples/forum/main.mjs
docs/3-web-servers/07-database/_samples/forum/main.mjs
docs/3-web-servers/08-cookie/_samples/profile/main.mjs

公式がつけてたので、つけました。cf. https://nodejs.org/api/fs.html#file-system

Change import from `fs` to `node:fs`

---

docs/1-trial-session/10-array/_samples/array-max/script.js
docs/1-trial-session/10-array/index.mdx

不要なコメント (消したはずだが...) と余計なテストコードを削除

Delete unnecessary commentout

---

docs/3-web-servers/06-get-post/_samples/forum/index.html
docs/3-web-servers/06-get-post/_samples/forum/main.mjs

#657 ではデータベースの解答のみしか修正されていなかったため、他の解答も #657 に合わせました。

Update answer of forum in form section

---

src/components/Term/definitions.js

Reactの章で`Term`タグが壊れているのを修正

---

docs/2-browser-apps/03-class/index.mdx

クラスの節の最後にある試行問題を削除しました。難しすぎると思うので。あと、コミットが混ざらないようにPR作りなおしました

delete class question

---

docs/3-web-servers/04-module/_samples/read-file-sync/main.mjs
docs/3-web-servers/04-module/_samples/read-file-sync/sample.txt
docs/3-web-servers/04-module/_samples/write-file-sync/main.mjs
docs/3-web-servers/04-module/index.mdx

`readFileSync`、`writeFileSync`の例を修正

---

docs/2-browser-apps/03-class/index.mdx

#742 からメソッドの解答例に関するものを抽出しました。
他の差分は別で取り出します。

メソッドの演習と解答例を修正

---

docs/2-browser-apps/03-class/index.mdx

継承の演習問題にコンストラクタを追加

---

docs/2-browser-apps/03-class/_samples/inheritance-class-SeniorStudent/script.js
docs/2-browser-apps/03-class/_samples/method-incrementAge/script.js
docs/2-browser-apps/03-class/index.mdx

CodeSandboxに表示される解答の更新を忘れていたため、更新しました。もともと差分があったため、Markdownの方を変えたものもあります。

CodeSandboxに表示される解答が更新されていなかったため、更新

---

docs/3-web-servers/07-get-post/index.mdx
docs/3-web-servers/08-database/index.mdx

リダイレクトの説明を動かした。

---

docs/3-web-servers/08-database/index.mdx

「データベース」の章のタイポを修正
